### ISSUE TITLE
Set this module in french

### ISSUE THREAD

**Issue by DarkScientist** [magician11/speech-to-text-demo#1]
Hi, how can we turn this module in French?
Thanks

**Comment by magician11** [comment]
Good question @DarkScientist The UI doesn't currently support this, even though [the npm module I built](https://www.npmjs.com/package/speech-to-text) does.

The UI should show language options. I'll implement it, and comment here when I have.

**Comment by magician11** [comment]
Ok I've updated this for you @DarkScientist 

![screen shot 2018-12-28 at 3 35 58 pm](https://user-images.githubusercontent.com/3735849/50500463-5cdfb080-0ab6-11e9-87a2-e5d1487ec98b.png)

Thanks for your feedback. Anything else, let me know.

**Comment by DarkScientist** [comment]
Hi, thanks you a lot!
